
import React from 'react';
import { useParams } from 'wouter';

const PortalView: React.FC = () => {
  const params = useParams();
  const linkToken = params?.token;

  return (
    <div className="p-10 max-w-4xl mx-auto text-center">
      <h1 className="text-3xl font-bold text-indigo-800 mb-4">
        Your Personalized Tour Summary
      </h1>
      <p className="text-lg text-gray-600 mb-8">
        Generated by Sarah Chen at THE JACKSON.
      </p>

      <div className="border p-6 rounded-lg bg-white shadow-lg">
        <p className="text-xl font-semibold">Token: {linkToken}</p>
        <p className="text-gray-500 mt-2">
          [Future: Display photos and details of your toured units here.]
        </p>
        <p className="mt-4 text-sm text-green-600">
          This link is valid for 30 days.
        </p>
      </div>
    </div>
  );
};

export default PortalView;
